-- ====================================================================
-- SUPABASE DATABASE CLEANUP & SCHEMA FOR MALCONNEXUS (3 ACCOUNTS ONLY)
-- ====================================================================
-- Copy and paste this script into your Supabase SQL Editor to:
-- 1. Wipe all fake/sample tasks and activities
-- 2. Delete any unauthorized/fake user profiles
-- 3. Ensure strictly the 3 Malconnexus accounts exist
-- ====================================================================

-- 1. WIPE ALL FAKE TASKS AND ACTIVITIES
TRUNCATE TABLE activities RESTART IDENTITY CASCADE;
TRUNCATE TABLE tasks RESTART IDENTITY CASCADE;

-- 2. PROFILES TABLE (Strictly 3 authorized accounts)
CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT PRIMARY KEY,
  fname TEXT NOT NULL,
  lname TEXT,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'manager', 'member', 'viewer')),
  dept TEXT,
  status TEXT DEFAULT 'online' CHECK (status IN ('online', 'away', 'offline')),
  avatar_class TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Delete any profiles that are NOT one of the 3 official Malconnexus emails
DELETE FROM profiles 
WHERE email NOT IN ('admin@malconnexus.com', 'preetam@malconnexus.com', 'staff@malconnexus.com');

-- Upsert the 3 official accounts
INSERT INTO profiles (id, fname, lname, email, role, dept, status, avatar_class)
VALUES 
  (1, 'Admin', 'User', 'admin@malconnexus.com', 'admin', 'Management', 'online', 'avatar-a'),
  (2, 'Preetam', '', 'preetam@malconnexus.com', 'manager', 'Engineering', 'online', 'avatar-b'),
  (3, 'Staff', 'Member', 'staff@malconnexus.com', 'member', 'Operations', 'away', 'avatar-c')
ON CONFLICT (id) DO UPDATE SET 
  fname = EXCLUDED.fname, 
  lname = EXCLUDED.lname, 
  email = EXCLUDED.email, 
  role = EXCLUDED.role, 
  dept = EXCLUDED.dept, 
  avatar_class = EXCLUDED.avatar_class;

-- 3. TASKS TABLE
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  "desc" TEXT DEFAULT '',
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
  status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'inprogress', 'review', 'done')),
  tag TEXT NOT NULL DEFAULT 'work' CHECK (tag IN ('work', 'personal', 'dev', 'design', 'review', 'urgent')),
  quadrant TEXT NOT NULL DEFAULT 'q2' CHECK (quadrant IN ('q1', 'q2', 'q3', 'q4')),
  due TEXT,
  assigned_to BIGINT REFERENCES profiles(id) ON DELETE SET NULL,
  completed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ACTIVITIES TABLE
CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('create', 'update', 'complete', 'delete', 'assign', 'comment')),
  user_id BIGINT REFERENCES profiles(id) ON DELETE CASCADE,
  task_id BIGINT REFERENCES tasks(id) ON DELETE SET NULL,
  text TEXT NOT NULL,
  target_user_id BIGINT REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access profiles" ON profiles;
CREATE POLICY "Public access profiles" ON profiles FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access tasks" ON tasks;
CREATE POLICY "Public access tasks" ON tasks FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access activities" ON activities;
CREATE POLICY "Public access activities" ON activities FOR ALL USING (true) WITH CHECK (true);

-- Enable Real-time Publication
ALTER PUBLICATION supabase_realtime ADD TABLE tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE activities;
ALTER PUBLICATION supabase_realtime ADD TABLE profiles;
